### ISSUE TITLE
createDirectory should fail specifically if the directory it's asked to create exists.

### ISSUE THREAD

**Issue by pontus** [nextflow-io/nextflow-s3fs#27]
For backstory, see https://nextflow.slack.com/archives/C02T97HAV5M/p1655317064553369

It appears there's a likely issue when using s3fs and `createDirectories` in `java.nio.Files` - it expects `createDirectory` from the filesystem provider to raise an `FileAlreadyExistsException` if the directory exists whereas s3fs doesn't check and goes on to do a `putObject`.

I don't know how that's contractually handled for "directories" in AWS s3, but it seems (see backstory) one can at least get a thrown `IOException` because AWS s3 returns a 503 Slowdown when called for the same object "simultaneously". 

There's a fixme at https://github.com/nextflow-io/nextflow-s3fs/blob/master/src/main/java/com/upplication/s3fs/S3FileSystemProvider.java#L469 for this already.

**Comment by jwarwick-delfi** [comment]
If it helps, I think this traceback is the "smoking gun":
```
Jun-15 10:33:47.760 [Actor Thread 16] ERROR nextflow.processor.TaskProcessor - Error executing process > '(redacted) (1)'

Caused by:
Please reduce your request rate. (Service: Amazon S3; Status Code: 503; Error Code: SlowDown; Request ID: MD7FTB7H2G8PMWJ7; S3 Extended Request ID: iMEr1D6neySFcquJdk/oZuF/XpwoxGzdIcV3fmD1USPqb4fwIAKq6hcQNO8jkRgAWkAmxZvSH0DBAjSYvqVzgg==; Proxy: null)

com.amazonaws.services.s3.model.AmazonS3Exception: Please reduce your request rate. (Service: Amazon S3; Status Code: 503; Error Code: SlowDown; Request ID: MD7FTB7H2G8PMWJ7; S3 Extended Request ID: iMEr1D6neySFcquJdk/oZuF/XpwoxGzdIcV3fmD1USPqb4fwIAKq6hcQNO8jkRgAWkAmxZvSH0DBAjSYvqVzgg==; Proxy: null)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
...
at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6508)
at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1856)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1816)
at com.upplication.s3fs.AmazonS3Client.putObject(AmazonS3Client.java:132)
at com.upplication.s3fs.S3FileSystemProvider.createDirectory(S3FileSystemProvider.java:486)
at java.base/java.nio.file.Files.createDirectory(Files.java:690)
at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
at java.base/java.nio.file.Files.createDirectories(Files.java:743)
at java_nio_file_Files$createDirectories.call(Unknown Source)
at nextflow.extension.FilesEx.mkdirs(FilesEx.groovy:491)
at nextflow.file.FilePorter.getCacheDir0(FilePorter.groovy:310)
at nextflow.file.FilePorter.getCachePathFor(FilePorter.groovy:302)
at nextflow.file.FilePorter$Batch.addToForeign(FilePorter.groovy:192)
at nextflow.file.FilePorter$Batch$addToForeign.call(Unknown Source)
at nextflow.processor.TaskProcessor.normalizeInputToFiles(TaskProcessor.groovy:1724)
...
at nextflow.processor.TaskProcessor.makeTaskContextStage2(TaskProcessor.groovy:1937)
```
